---
title: "Analysis on yelp reviews"
author: "Huitong Kou, Zihang Wang, Peibin Rui"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal

To provide

- Data-driven actionable plan to help business owners improve their ratings on Yelp. 

- Key useful, analytical insights from the data (e.g. plots, tables, models, inferential methods, etc.) .
- A demonstration of your Shiny application.

## Data Cleaning

Limited by the computing power, we chose to foucus on some restaurant whose category had the word "steak".

The `yelp.ipynb` in code folder is used to clean the data and create the word frequency table and the large word embedding table with original views.

After filtering and combination, the `steak_cleaned.csv` has 33629 rows × 6085 columns.

## Insights about certain industry

words distribution in reviews of different stars

focus on certain district like Madison

compare great and awful restaurant from words of food type,  etc

statistical test

...

## Actionable plan

food, drink, wifi, parking, price

## Shiny App

link

## Code Directions

The Rmd file is for knitting the summary file.

All the data are stored in the `data` directory.










